import 'dart:ui';
import 'package:flutter/material.dart';
const KPrimryColor=Color(0Xff274460);
const KSecondryColor=Color(0Xff006488);
const KLogo="assets/images/scholar.png";
const KMessageCollection='messages';
const KMessage='message';
const KCreatedAt='createdAt';
const KId='id';