// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7wvMNWlrZlFFDtNh3oBspG1-v1vgobt0',
    appId: '1:845603327622:web:1ed4a5ceb36f795af08b07',
    messagingSenderId: '845603327622',
    projectId: 'chatapp-5af22',
    authDomain: 'chatapp-5af22.firebaseapp.com',
    storageBucket: 'chatapp-5af22.appspot.com',
    measurementId: 'G-RLJ4X54863',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXgcvyprXF53D6f2-qGzlixqbORowx0Qw',
    appId: '1:845603327622:android:e96b4a0fe4eacca2f08b07',
    messagingSenderId: '845603327622',
    projectId: 'chatapp-5af22',
    storageBucket: 'chatapp-5af22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjPZBHHlZtTArodUblcDdUp3RV8Vw8LAg',
    appId: '1:845603327622:ios:e0dc1e4e51bf4c3af08b07',
    messagingSenderId: '845603327622',
    projectId: 'chatapp-5af22',
    storageBucket: 'chatapp-5af22.appspot.com',
    iosClientId: '845603327622-33q9gdsdsvntaae8mkdp6e7j2kknunhk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
